### ISSUE TITLE
collect_assignment and derived scripts require API change

### ISSUE THREAD

**Issue by rgwott** [snadi/UsefulCourseScripts#1]
Hi Sarah,
In using Karim's 229 fork of this repo, I had to change line 27 of collect_assignments.py from
	for repo in course.repositories():
to
	for repo in course.iter_repos():

The problem was that objects of class Organization do not have a repositories() method.
My environment runs python 3.5, although I also tested it with python 2.7. In both cases, I used package github3.py version 0.9.6, installed via pip. The library's documentation follows:
https://github3py.readthedocs.io/en/0.9.6/orgs.html

Thanks!

**Comment by snadi** [comment]
Thanks... I'll take a look into it. Note that the scripts here may be more useful to you (not sure if they have the same issue or not) https://github.com/cmput201-w18/GitHubClassroomMgmt

**Comment by rgwott** [comment]
Definitely, those are the ones I am using. But I figured that the issue should be opened on the original repo.
